swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/accounts/{accountId}/transactions:
    get:
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for all user transactions
      consumes:
          - application/json
      produces:
           - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT Token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: id of the account to get
      responses:
        '200':
          description: Api for all user transactions
          schema:
            items:
              $ref: '#/definitions/TransactionsList'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: User Transaction API
      description: Api for one user transaction
      consumes:
          - application/json
      produces:
          - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: id of the account to get
        - in: path
          name: transactionId
          type: integer
          required: true
          description: id of the transaction to get
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid token
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions Module
      summary: User Transaction API
      description: API for transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: id of the account to get
        - in: path
          name: transactionId
          type: integer
          required: true
          description: id of the transaction to get
        - in: body
          name: details
          description: the transaction to update
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successully
          schema:
            $ref: '#/definitions/TransactionsList'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transactions Module
      summary: User Transaction API
      description: API for transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: id of the account to get
        - in: path
          name: transactionId
          type: integer
          required: true
          description: id of the transaction to delete
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
           
definitions:
  TransactionsList:
    type: object
    properties:
      idAccount:
        type: number
      idTransaction:
        type: number
     
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
  Transaction:
    type: object
    properties:
      idTransaction:
        type: number
      idAccount:
        type: number
      Type:
        type: string
      Category:
        type: string
      Notes:
        type: string