swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/accounts/{accountId}/transactions:
    get:
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for all user transactions
      consumes:
          - application/json
      produces:
           - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT Token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: id of the account to get
      responses:
        '200':
          description: Api for one user transaction
          schema:
            items:
              $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: User Transactions API
      description: Api for one user transaction
      consumes:
          - application/json
      produces:
          - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: id of the account to get
        - in: path
          name: transactionId
          type: integer
          required: true
          description: id of the transaction to get
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid token
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: id of the account to get
        - in: path
          name: transactionId
          type: integer
          required: true
          description: id of the transaction to get
        - in: body
          name: details
          description: the transaction to update
          required: true
          schema:
            $ref: '#/definitions/Transactions'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
         
definitions:

    Transactions:
        type: 'object'
        properties:
            transaction:
                type: 'object'
                properties:
                    idAccount:
                        type: 'integer'
                    idTransaction:
                        type: 'integer'
                    date:
                        type: 'string'
                    description:
                        type: 'string'
                    amount:
                        type: 'integer'
                    type:
                        type: 'string'
                    category:
                        type: 'string'
                    notes:
                        type: 'string'
